-- Guías de salida sin técnico asignado.
--
-- Igual que las evidencias (20260925120000_evidencias_tecnico_opcional): toda
-- guía se guardaba a nombre de un técnico (id_tecnico NOT NULL), así que un rol
-- de gestión no podía registrarla en un servicio que todavía no tenía técnico
-- ("No hay técnico asignado al servicio para asociar la guía"), y el cierre de
-- un servicio sin técnico fallaba al crear la guía. Ahora la columna admite
-- NULL y, en ese caso, el autor es el usuario de `user_id_registration`.
--
-- La FK a tbl_tecnicos se mantiene tal cual (ON DELETE RESTRICT). Quitar el NOT
-- NULL es un cambio de catálogo: no reescribe la tabla ni toca las filas.
ALTER TABLE "tbl_servicios_guias" ALTER COLUMN "id_tecnico" DROP NOT NULL;
